-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'LAWYER', 'BAIL_BONDS', 'PROCESS_SERVER', 'APARTMENT_MANAGER', 'ADMIN');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'USER';
